language: cpp
compiler: g++-4.8

script:
    - make CXX=g++-4.8 && exit 0 

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq gcc-4.8
- sudo apt-get install -qq g++-4.8
